[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".oh-my-bash"]
    type = "git-repo"
    url = "https://github.com/ohmybash/oh-my-bash"
    refreshPeriod = "168h"

{{ if not .noGUI }}
[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    refreshPeriod = "168h"
{{ end }}
