[".vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

[".oh-my-bash"]
    type = "git-repo"
    url = "https://github.com/ohmybash/oh-my-bash"
    refreshPeriod = "168h"

{{ if not .noGUI }}
[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    refreshPeriod = "168h"
{{ end }}

{{ if and .unRootMode (eq .chezmoi.arch "amd64")}}

{{/* 手動安裝 eza */ -}}
{{ $ezaVersion := "v0.21.3" -}}
[".local/bin/eza"]
    type = "archive-file"
    url = "https://github.com/eza-community/eza/releases/download/{{ $ezaVersion }}/eza_x86_64-unknown-{{ .chezmoi.os }}-gnu.tar.gz"
    path = "./eza"

{{/* 手動安裝 neovim (已在install-packages.sh處理) */ -}}
{{/* 手動安裝 zsh (已在install-packages.sh處理) */ -}}
{{/* 手動安裝 lazygit */ -}}
{{ end }}
