# macOS ------------------------------------------------------------------------
# TODO: python-ollama尚未處理
[packages.darwin]
taps = [
  'laishulu/homebrew',
]

brews = [
  'chezmoi',
  'git',
  'lazygit',
  'zsh',
  'vim',
  'neovim',
  'lsix',
  'eza',
  'grc',
  'zellij',
  'ranger',
  'cmake',
  'python',
  'go',
  'nodejs',
  'java',
  'jstkdng/programs/ueberzugpp',
  'macism',
  'tmux',
  'htop',
  'bmon',
]

casks = [
  'iterm2',
#  'neovide',
#  'alacritty',
#  'macvim',
]

# Ubuntu -----------------------------------------------------------------------
# Ubuntu 24.04.2 LTS 測試過
# TODO: lazygit, chezmoi, python-ollama尚未處理
[packages.linux.ubuntu]
apt = [
  'sudo',
  'zsh',
  'vim',
  'git',
  'gcc',
  'eza',
  'neovim',
  'ueberzug',
  'ripgrep',
  'tree-sitter-cli',
  'tmux',
  'htop',
  'bmon',
]

# Debian -----------------------------------------------------------------------
# Debian 12, Debian 13 測試過
# TODO: chezmoi, python-ollama尚未處理
# 特別備註:
#   Debain 12 (bookworm) 沒有eza，但是有exa
#   Debain 12 (bookworm) 沒有ueberzugpp，但是有ueberzug
#   Debain 12 (bookworm) neovim版本太舊 0.7，lazy無法用，故在shell腳本特殊處理
[packages.linux.debian]
apt_12 = [
  'exa',
]

apt = [
  'sudo',
  'zsh',
  'vim',
  'git',
  'gcc',
  'ripgrep',
  'tmux',
  'htop',
  'bmon',
]

apt_13 = [
  'eza',
  'neovim',
  'tree-sitter-cli',
  'python3-ollama',
  'lazygit',
]

# Arch Linux -------------------------------------------------------------------
[packages.linux.arch]
pacman_force = [
  'archlinux-keyring',
  'llvm',
  'llvm-libs',
  'sudo',
  'git',
]

pacman = [
  'chezmoi',
  'lazygit',
  'base-devel',
  'fakeroot',
  'gcc',
  'cmake',
  'zsh',
  'lsix',
  'imagemagick',
  'ueberzugpp',
  'eza',
  'grc',
  'zellij',
  'ranger',
  'neovim',
  'ripgrep',
  'tree-sitter',
  'tmux',
  'htop',
  'bmon',
]
pacman_nogui = [
  'vim',
]
pacman_gui = [
  'gvim',
#  'neovide',
]

aur = [
  'python-ollama',
]

aur_gui = [
  'alacritty-sixel-git',
  'winscp',
]

# Manjaro Linux ----------------------------------------------------------------
[packages.linux.manjaro]
pacman_force = [
  'archlinux-keyring',
  'libpamac',
  'llvm',
  'llvm-libs',
]

pacman = [
  'chezmoi',
  'yay',
  'git',
  'lazygit',
  'base-devel',
  'fakeroot',
  'gcc',
  'cmake',
  'zsh',
  'lsix',
  'imagemagick',
  'ueberzugpp',
  'eza',
  'grc',
  'zellij',
  'ranger',
  'neovim',
  'python',
  'go',
  'nodejs',
  'npm',
  'jdk-openjdk',
  'ripgrep',
  'tree-sitter',
  'tree-sitter-bash',
  'tree-sitter-cli',
  'tmux',
  'htop',
  'bmon',
]
pacman_nogui = [
  'vim',
]
pacman_gui = [
  'gvim',
#  'neovide',
  'foot',
]

aur = [
  'python-ollama',
]

aur_gui = [
  'glrnvim',
  'alacritty-sixel-git',
  'winscp',
]
