[packages.darwin]
brews = [
  'chezmoi',
  'git',
  'zsh',
  'vim',
  'neovim',
  'neovide',
  'lsix',
  'eza',
  'grc',
  'zellij',
  'ranger',
  'cmake',
  'python',
  'go',
  'nodejs',
  'java',
  'jstkdng/programs/ueberzugpp',
]

casks = [
  'iterm2',
#  'alacritty',
#  'macvim',
]

[packages.linux.manjaro]
pacman_force = [
  'archlinux-keyring',
  'libpamac',
  'llvm',
  'llvm-libs',
]

pacman = [
  'chezmoi',
  'yay',
  'base-devel',
  'fakeroot',
  'gcc',
  'cmake',
  'lsix',
  'eza',
  'grc',
  'zellij',
  'ranger',
  'vim',
  'gvim',
  'neovim',
  'neovide',
  'python',
  'go',
  'nodejs',
  'npm',
  'jdk-openjdk',
]

aur = [
  'alacritty-sixel-git',
  'winscp',
]
