# macOS ------------------------------------------------------------------------
[packages.darwin]
brews = [
  'chezmoi',
  'git',
  'zsh',
  'vim',
  'neovim',
  'neovide',
  'lsix',
  'eza',
  'grc',
  'zellij',
  'ranger',
  'cmake',
  'python',
  'go',
  'nodejs',
  'java',
  'jstkdng/programs/ueberzugpp',
]

casks = [
  'iterm2',
#  'alacritty',
#  'macvim',
]

# Arch Linux -------------------------------------------------------------------
[packages.linux.arch]
pacman_force = [
  'archlinux-keyring',
  'llvm',
  'llvm-libs',
]

pacman = [
  'chezmoi',
  'git',
  'base-devel',
  'fakeroot',
  'gcc',
  'cmake',
  'lsix',
  'ueberzugpp',
  'eza',
  'grc',
  'zellij',
  'ranger',
  'vim',
  'neovim',
  'python',
  'go',
  'nodejs',
  'npm',
  'jdk-openjdk',
]

# Manjaro Linux ----------------------------------------------------------------
[packages.linux.manjaro]
pacman_force = [
  'archlinux-keyring',
  'libpamac',
  'llvm',
  'llvm-libs',
]

pacman = [
  'chezmoi',
  'yay',
  'git',
  'base-devel',
  'fakeroot',
  'gcc',
  'cmake',
  'lsix',
  'ueberzugpp',
  'eza',
  'grc',
  'zellij',
  'ranger',
  'vim',
  'neovim',
  'python',
  'go',
  'nodejs',
  'npm',
  'jdk-openjdk',
]
pacman_gui = [
  'gvim',
  'neovide',
]

aur = [
]

aur_gui = [
  'alacritty-sixel-git',
  'winscp',
]
